run:
  timeout: 3m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - api
    - build
    - docs
    - configs
    - scripts
    - mock
  skip-dirs-use-default: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  errcheck:
    check-blank: true

issues:
  include:
    - EXC0002 # disable excluding of issues about comments from golint
    - EXC0011 # disable excluding package comments
    # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "
